Update junit
Fix this error:

```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /var/lib/jenkins/workspace/MatchSamples/src/test/java/org/pankratzlab/internal/gwas/REvalTest.java:[8,36] package org.junit.jupiter.api does not exist
```